name: Build & deploy release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8] # Add numbers as Java is updated
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'

      - name: Set version to release
        run: ./gradlew unSnapshotVersion commitNewVersion

      - name: Build & deploy to Nexus
        env:
          REPO_PASSWORD: ${{ secrets.NEXUS_CI }}
        run: ./gradlew build --no-daemon

      - name: Push to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
